// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHLir3rXzTWuRJOz-Mz-jwpj-MnBldkd8',
    appId: '1:295066253466:web:3ec18663d7a83714064723',
    messagingSenderId: '295066253466',
    projectId: 'test-intern-28907',
    authDomain: 'test-intern-28907.firebaseapp.com',
    storageBucket: 'test-intern-28907.appspot.com',
    measurementId: 'G-CYNJ45PYH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWjVmDhOZQmwUtK2AuLYSt7vXyIPOnCuw',
    appId: '1:295066253466:android:8d203cb39dd735cb064723',
    messagingSenderId: '295066253466',
    projectId: 'test-intern-28907',
    storageBucket: 'test-intern-28907.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXM9P8ijQAbjF4G0QiNhjkJmOazFTaCTU',
    appId: '1:295066253466:ios:f39706e2f8d6b5c1064723',
    messagingSenderId: '295066253466',
    projectId: 'test-intern-28907',
    storageBucket: 'test-intern-28907.appspot.com',
    iosBundleId: 'com.example.testIntern',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXM9P8ijQAbjF4G0QiNhjkJmOazFTaCTU',
    appId: '1:295066253466:ios:38bb438138aef455064723',
    messagingSenderId: '295066253466',
    projectId: 'test-intern-28907',
    storageBucket: 'test-intern-28907.appspot.com',
    iosBundleId: 'com.example.testIntern.RunnerTests',
  );
}
